### ISSUE TITLE
Yoda 1.6 invitation screen: Terms of use are all UU

### ISSUE THREAD

**Issue by bgoli** [vu-rdm-tech/yoda-pilot#39] opened 2021-01-12 12:10 UTC
![image](https://user-images.githubusercontent.com/5011985/104312754-57a40180-54d7-11eb-911a-ceb7223229dc.png)

**Comment by bgoli** [comment] 2021-01-14 17:36
@peer35 is this just an artefact of the test environment? If so it can be closed.

**Comment by peer35** [comment] 2021-06-15 14:54
Duplicate of https://github.com/vu-rdm-tech/yoda-pilot/issues/15

**Closed as completed by peer35** 2021-06-15 14:54 UTC
Labels: yoda1.6
